export const CLOSE_APPLICATION = 'CLOSE_APPLICATION';
export const HIDE_APPLICATION = 'HIDE_APPLICATION';
export const REGISTER_SHOW_APPLICATION_HOTKEY =
  'REGISTER_SHOW_APPLICATION_HOTKEY';
export const NAVIGATE_HOME = 'NAVIGATE_HOME';
export const PROMPT_FOR_DIRECTORY = 'PROMPT_FOR_DIRECTORY';
export const SCAN_DIRECTORY = 'SCAN_DIRECTORY';
export const REPORT_EXCEPTION = 'REPORT_EXCEPTION';
export const REPORT_ACTIVE_ROUTE = 'REPORT_ACTIVE_ROUTE';
export const INITIALIZE_FILE_WATCHER = 'INITIALIZE_FILE_WATCHER';
export const ENABLE_FILE_WATCHING = 'ENABLE_FILE_WATCHING';
export const DIRECTORIES_TO_FILE_WATCHER = 'DIRECTORIES_TO_FILE_WATCHER';
export const FILTERED_PATTERNS_TO_FILE_WATCHER =
  'FILTERED_PATTERNS_TO_FILE_WATCHER';
export const ON_PROJECT_ADDED = 'ON_PROJECT_ADDED';
export const ON_PROJECT_CHANGED = 'ON_PROJECT_CHANGED';
export const ON_PROJECT_REMOVED = 'ON_PROJECT_REMOVED';
export const DETERMINE_NESTED_PROJECTS = 'DETERMINE_NESTED_PROJECTS';
export const OPEN_PROJECT_DIRECTORY = 'OPEN_PROJECT_DIRECTORY';
