export const CLOSE_APPLICATION = 'CLOSE_APPLICATION';
export const HIDE_APPLICATION = 'HIDE_APPLICATION';
export const REGISTER_SHOW_APPLICATION_HOTKEY =
    'REGISTER_SHOW_APPLICATION_HOTKEY';

export const NAVIGATE_HOME = 'NAVIGATE_HOME';
